import 'package:antd_ui/constants/constants.dart';
import 'package:flutter/material.dart';

class AntdIcon extends StatefulWidget {
  final IconData? icon;
  final double? size;
  final Color? color;
  final Color? hoverColor;
  final VoidCallback? onClick;

  /// 图标语义描述信息，无障碍信息
  final String? semanticLabel;
  const AntdIcon(
    this.icon, {
    super.key,
    this.size = iIconSize,
    this.color = iBlack,
    this.semanticLabel,
    this.onClick,
    this.hoverColor = iPrimaryTextHover,
  });

  @override
  State<AntdIcon> createState() => _AntdIconState();
}

class _AntdIconState extends State<AntdIcon> {
  bool isHover = false;
  Widget iconWidget() {
    return InkWell(
      onTap: widget.onClick,
      child: RichText(
        overflow: TextOverflow.visible,
        text: TextSpan(
          text: String.fromCharCode(widget.icon!.codePoint),
          style: TextStyle(
            inherit: false,
            color: isHover ? widget.hoverColor : widget.color,
            fontSize: widget.size,
            fontFamily: widget.icon!.fontFamily,
            package: 'antd_ui',
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Semantics(
      label: widget.semanticLabel,
      child: widget.icon == null
          ? SizedBox(width: widget.size, height: widget.size)
          : MouseRegion(
              cursor: SystemMouseCursors.click,
              onEnter: (event) {
                setState(() {
                  isHover = true;
                });
              },
              onExit: (event) {
                setState(() {
                  isHover = false;
                });
              },
              child: ExcludeSemantics(
                child: IntrinsicWidth(
                  child: IntrinsicHeight(
                    child: Center(
                      child: iconWidget(),
                    ),
                  ),
                ),
              ),
            ),
    );
  }
}

class AntdIconData {
  static const IconData wrench = IconData(0xe84b, fontFamily: 'Antd');
  static const IconData dingtalk = IconData(0xe94b, fontFamily: 'Antd');
  static const IconData tags = IconData(0xe84c, fontFamily: 'Antd');
  static const IconData androidfill = IconData(0xe94c, fontFamily: 'Antd');
  static const IconData scissor = IconData(0xe84d, fontFamily: 'Antd');
  static const IconData applefill = IconData(0xe94d, fontFamily: 'Antd');
  static const IconData mr = IconData(0xe84e, fontFamily: 'Antd');
  static const IconData html5fill = IconData(0xe94e, fontFamily: 'Antd');
  static const IconData share = IconData(0xe84f, fontFamily: 'Antd');
  static const IconData windowsfill = IconData(0xe94f, fontFamily: 'Antd');
  static const IconData branches = IconData(0xe850, fontFamily: 'Antd');
  static const IconData qq = IconData(0xe950, fontFamily: 'Antd');
  static const IconData fork = IconData(0xe851, fontFamily: 'Antd');
  static const IconData twitter = IconData(0xe951, fontFamily: 'Antd');
  static const IconData shrink = IconData(0xe852, fontFamily: 'Antd');
  static const IconData skypefill = IconData(0xe952, fontFamily: 'Antd');
  static const IconData arrawsalt = IconData(0xe853, fontFamily: 'Antd');
  static const IconData weibo = IconData(0xe953, fontFamily: 'Antd');
  static const IconData verticalright = IconData(0xe854, fontFamily: 'Antd');
  static const IconData yuquefill = IconData(0xe954, fontFamily: 'Antd');
  static const IconData verticalleft = IconData(0xe855, fontFamily: 'Antd');
  static const IconData youtubefill = IconData(0xe955, fontFamily: 'Antd');
  static const IconData right = IconData(0xe856, fontFamily: 'Antd');
  static const IconData yahoofill = IconData(0xe956, fontFamily: 'Antd');
  static const IconData left = IconData(0xe857, fontFamily: 'Antd');
  static const IconData wechatfill = IconData(0xe957, fontFamily: 'Antd');
  static const IconData up = IconData(0xe858, fontFamily: 'Antd');
  static const IconData chromefill = IconData(0xe958, fontFamily: 'Antd');
  static const IconData down = IconData(0xe859, fontFamily: 'Antd');
  static const IconData alipaycirclefill = IconData(0xe959, fontFamily: 'Antd');
  static const IconData fullscreen = IconData(0xe85a, fontFamily: 'Antd');
  static const IconData aliwangwangfill = IconData(0xe95a, fontFamily: 'Antd');
  static const IconData fullscreenexit = IconData(0xe85b, fontFamily: 'Antd');
  static const IconData behancecirclefill = IconData(0xe95b, fontFamily: 'Antd');
  static const IconData doubleleft = IconData(0xe85c, fontFamily: 'Antd');
  static const IconData amazoncirclefill = IconData(0xe95c, fontFamily: 'Antd');
  static const IconData doubleright = IconData(0xe85d, fontFamily: 'Antd');
  static const IconData codepencirclefill = IconData(0xe95d, fontFamily: 'Antd');
  static const IconData arrowright = IconData(0xe85e, fontFamily: 'Antd');
  static const IconData codesandboxcirclef = IconData(0xe95e, fontFamily: 'Antd');
  static const IconData arrowup = IconData(0xe85f, fontFamily: 'Antd');
  static const IconData dropboxcirclefill = IconData(0xe95f, fontFamily: 'Antd');
  static const IconData arrowleft = IconData(0xe860, fontFamily: 'Antd');
  static const IconData githubfill = IconData(0xe960, fontFamily: 'Antd');
  static const IconData arrowdown = IconData(0xe861, fontFamily: 'Antd');
  static const IconData dribbblecirclefill = IconData(0xe961, fontFamily: 'Antd');
  static const IconData upload = IconData(0xe862, fontFamily: 'Antd');
  static const IconData googlepluscirclef = IconData(0xe962, fontFamily: 'Antd');
  static const IconData columheight = IconData(0xe863, fontFamily: 'Antd');
  static const IconData mediumcirclefill = IconData(0xe963, fontFamily: 'Antd');
  static const IconData verticalalignbotto = IconData(0xe864, fontFamily: 'Antd');
  static const IconData qqcirclefill = IconData(0xe964, fontFamily: 'Antd');
  static const IconData verticalalignmiddl = IconData(0xe865, fontFamily: 'Antd');
  static const IconData iecirclefill = IconData(0xe965, fontFamily: 'Antd');
  static const IconData totop = IconData(0xe866, fontFamily: 'Antd');
  static const IconData googlecirclefill = IconData(0xe966, fontFamily: 'Antd');
  static const IconData verticalaligntop = IconData(0xe867, fontFamily: 'Antd');
  static const IconData dingtalkcirclefill = IconData(0xe967, fontFamily: 'Antd');
  static const IconData download = IconData(0xe868, fontFamily: 'Antd');
  static const IconData sketchcirclefill = IconData(0xe968, fontFamily: 'Antd');
  static const IconData sortdescending = IconData(0xe869, fontFamily: 'Antd');
  static const IconData slackcirclefill = IconData(0xe969, fontFamily: 'Antd');
  static const IconData sortascending = IconData(0xe86a, fontFamily: 'Antd');
  static const IconData twittercirclefill = IconData(0xe96a, fontFamily: 'Antd');
  static const IconData fall = IconData(0xe86b, fontFamily: 'Antd');
  static const IconData taobaocirclefill = IconData(0xe96b, fontFamily: 'Antd');
  static const IconData swap = IconData(0xe86c, fontFamily: 'Antd');
  static const IconData weibocirclefill = IconData(0xe96c, fontFamily: 'Antd');
  static const IconData stock = IconData(0xe86d, fontFamily: 'Antd');
  static const IconData zhihucirclefill = IconData(0xe96d, fontFamily: 'Antd');
  static const IconData rise = IconData(0xe86e, fontFamily: 'Antd');
  static const IconData redditcirclefill = IconData(0xe96e, fontFamily: 'Antd');
  static const IconData indent = IconData(0xe86f, fontFamily: 'Antd');
  static const IconData alipaysquarefill = IconData(0xe96f, fontFamily: 'Antd');
  static const IconData outdent = IconData(0xe870, fontFamily: 'Antd');
  static const IconData dingtalksquarefill = IconData(0xe970, fontFamily: 'Antd');
  static const IconData menu = IconData(0xe871, fontFamily: 'Antd');
  static const IconData codesandboxsquaref = IconData(0xe971, fontFamily: 'Antd');
  static const IconData unorderedlist = IconData(0xe872, fontFamily: 'Antd');
  static const IconData behancesquarefill = IconData(0xe972, fontFamily: 'Antd');
  static const IconData orderedlist = IconData(0xe873, fontFamily: 'Antd');
  static const IconData amazonsquarefill = IconData(0xe973, fontFamily: 'Antd');
  static const IconData alignright = IconData(0xe874, fontFamily: 'Antd');
  static const IconData codepensquarefill = IconData(0xe974, fontFamily: 'Antd');
  static const IconData aligncenter = IconData(0xe875, fontFamily: 'Antd');
  static const IconData dribbblesquarefill = IconData(0xe975, fontFamily: 'Antd');
  static const IconData alignleft = IconData(0xe876, fontFamily: 'Antd');
  static const IconData dropboxsquarefill = IconData(0xe976, fontFamily: 'Antd');
  static const IconData piccenter = IconData(0xe877, fontFamily: 'Antd');
  static const IconData facebookfill = IconData(0xe977, fontFamily: 'Antd');
  static const IconData picright = IconData(0xe878, fontFamily: 'Antd');
  static const IconData googleplussquaref = IconData(0xe978, fontFamily: 'Antd');
  static const IconData picleft = IconData(0xe879, fontFamily: 'Antd');
  static const IconData googlesquarefill = IconData(0xe979, fontFamily: 'Antd');
  static const IconData bold = IconData(0xe87a, fontFamily: 'Antd');
  static const IconData instagramfill = IconData(0xe97a, fontFamily: 'Antd');
  static const IconData fontcolors = IconData(0xe87b, fontFamily: 'Antd');
  static const IconData iesquarefill = IconData(0xe97b, fontFamily: 'Antd');
  static const IconData exclaimination = IconData(0xe87c, fontFamily: 'Antd');
  static const IconData mediumsquarefill = IconData(0xe97c, fontFamily: 'Antd');
  static const IconData checkcircle = IconData(0xe77d, fontFamily: 'Antd');
  static const IconData fontsize = IconData(0xe87d, fontFamily: 'Antd');
  static const IconData linkedinfill = IconData(0xe97d, fontFamily: 'Antd');
  static const IconData ci = IconData(0xe77e, fontFamily: 'Antd');
  static const IconData infomation = IconData(0xe87e, fontFamily: 'Antd');
  static const IconData qqsquarefill = IconData(0xe97e, fontFamily: 'Antd');
  static const IconData dollar = IconData(0xe77f, fontFamily: 'Antd');
  static const IconData lineheight = IconData(0xe87f, fontFamily: 'Antd');
  static const IconData redditsquarefill = IconData(0xe97f, fontFamily: 'Antd');
  static const IconData compass = IconData(0xe780, fontFamily: 'Antd');
  static const IconData strikethrough = IconData(0xe880, fontFamily: 'Antd');
  static const IconData twittersquarefill = IconData(0xe980, fontFamily: 'Antd');
  static const IconData closecircle = IconData(0xe781, fontFamily: 'Antd');
  static const IconData underline = IconData(0xe881, fontFamily: 'Antd');
  static const IconData sketchsquarefill = IconData(0xe981, fontFamily: 'Antd');
  static const IconData frown = IconData(0xe782, fontFamily: 'Antd');
  static const IconData number = IconData(0xe882, fontFamily: 'Antd');
  static const IconData slacksquarefill = IconData(0xe982, fontFamily: 'Antd');
  static const IconData infocircle = IconData(0xe783, fontFamily: 'Antd');
  static const IconData italic = IconData(0xe883, fontFamily: 'Antd');
  static const IconData taobaosquarefill = IconData(0xe983, fontFamily: 'Antd');
  static const IconData leftcircle = IconData(0xe784, fontFamily: 'Antd');
  static const IconData code = IconData(0xe884, fontFamily: 'Antd');
  static const IconData weibosquarefill = IconData(0xe984, fontFamily: 'Antd');
  static const IconData downcircle = IconData(0xe785, fontFamily: 'Antd');
  static const IconData columnwidth = IconData(0xe885, fontFamily: 'Antd');
  static const IconData zhihusquarefill = IconData(0xe985, fontFamily: 'Antd');
  static const IconData euro = IconData(0xe786, fontFamily: 'Antd');
  static const IconData check = IconData(0xe886, fontFamily: 'Antd');
  static const IconData zoomout = IconData(0xe986, fontFamily: 'Antd');
  static const IconData copyright = IconData(0xe787, fontFamily: 'Antd');
  static const IconData ellipsis = IconData(0xe887, fontFamily: 'Antd');
  static const IconData apartment = IconData(0xe987, fontFamily: 'Antd');
  static const IconData minuscircle = IconData(0xe788, fontFamily: 'Antd');
  static const IconData dash = IconData(0xe888, fontFamily: 'Antd');
  static const IconData audio = IconData(0xe988, fontFamily: 'Antd');
  static const IconData meh = IconData(0xe789, fontFamily: 'Antd');
  static const IconData close = IconData(0xe889, fontFamily: 'Antd');
  static const IconData audiofill = IconData(0xe989, fontFamily: 'Antd');
  static const IconData pluscircle = IconData(0xe78a, fontFamily: 'Antd');
  static const IconData enter = IconData(0xe88a, fontFamily: 'Antd');
  static const IconData robot = IconData(0xe98a, fontFamily: 'Antd');
  static const IconData playcircle = IconData(0xe78b, fontFamily: 'Antd');
  static const IconData line = IconData(0xe88b, fontFamily: 'Antd');
  static const IconData zoomin = IconData(0xe98b, fontFamily: 'Antd');
  static const IconData questioncircle = IconData(0xe78c, fontFamily: 'Antd');
  static const IconData minus = IconData(0xe88c, fontFamily: 'Antd');
  static const IconData robotfill = IconData(0xe98c, fontFamily: 'Antd');
  static const IconData pound = IconData(0xe78d, fontFamily: 'Antd');
  static const IconData question = IconData(0xe88d, fontFamily: 'Antd');
  static const IconData bugfill = IconData(0xe98d, fontFamily: 'Antd');
  static const IconData rightcircle = IconData(0xe78e, fontFamily: 'Antd');
  static const IconData rollback = IconData(0xe88e, fontFamily: 'Antd');
  static const IconData bug = IconData(0xe98e, fontFamily: 'Antd');
  static const IconData smile = IconData(0xe78f, fontFamily: 'Antd');
  static const IconData smalldash = IconData(0xe88f, fontFamily: 'Antd');
  static const IconData audiostatic = IconData(0xe98f, fontFamily: 'Antd');
  static const IconData trademark = IconData(0xe790, fontFamily: 'Antd');
  static const IconData pause = IconData(0xe890, fontFamily: 'Antd');
  static const IconData comment = IconData(0xe990, fontFamily: 'Antd');
  static const IconData timecircle = IconData(0xe791, fontFamily: 'Antd');
  static const IconData bgcolors = IconData(0xe891, fontFamily: 'Antd');
  static const IconData signalfill = IconData(0xe991, fontFamily: 'Antd');
  static const IconData timeout = IconData(0xe792, fontFamily: 'Antd');
  static const IconData crown = IconData(0xe892, fontFamily: 'Antd');
  static const IconData verified = IconData(0xe992, fontFamily: 'Antd');
  static const IconData earth = IconData(0xe793, fontFamily: 'Antd');
  static const IconData drag = IconData(0xe893, fontFamily: 'Antd');
  static const IconData shortcutfill = IconData(0xe993, fontFamily: 'Antd');
  static const IconData yuan = IconData(0xe794, fontFamily: 'Antd');
  static const IconData desktop = IconData(0xe894, fontFamily: 'Antd');
  static const IconData videocameraadd = IconData(0xe994, fontFamily: 'Antd');
  static const IconData upcircle = IconData(0xe795, fontFamily: 'Antd');
  static const IconData gift = IconData(0xe895, fontFamily: 'Antd');
  static const IconData switchuser = IconData(0xe995, fontFamily: 'Antd');
  static const IconData warningcircle = IconData(0xe796, fontFamily: 'Antd');
  static const IconData stop = IconData(0xe896, fontFamily: 'Antd');
  static const IconData whatsapp = IconData(0xe996, fontFamily: 'Antd');
  static const IconData sync = IconData(0xe797, fontFamily: 'Antd');
  static const IconData fire = IconData(0xe897, fontFamily: 'Antd');
  static const IconData appstoreadd = IconData(0xe997, fontFamily: 'Antd');
  static const IconData transaction = IconData(0xe798, fontFamily: 'Antd');
  static const IconData thunderbolt = IconData(0xe898, fontFamily: 'Antd');
  static const IconData caretdown = IconData(0xe998, fontFamily: 'Antd');
  static const IconData undo = IconData(0xe799, fontFamily: 'Antd');
  static const IconData checkcirclefill = IconData(0xe899, fontFamily: 'Antd');
  static const IconData backward = IconData(0xe999, fontFamily: 'Antd');
  static const IconData redo = IconData(0xe79a, fontFamily: 'Antd');
  static const IconData leftcirclefill = IconData(0xe89a, fontFamily: 'Antd');
  static const IconData caretup = IconData(0xe99a, fontFamily: 'Antd');
  static const IconData reload = IconData(0xe79b, fontFamily: 'Antd');
  static const IconData downcirclefill = IconData(0xe89b, fontFamily: 'Antd');
  static const IconData caretright = IconData(0xe99b, fontFamily: 'Antd');
  static const IconData reloadtime = IconData(0xe79c, fontFamily: 'Antd');
  static const IconData minuscirclefill = IconData(0xe89c, fontFamily: 'Antd');
  static const IconData caretleft = IconData(0xe99c, fontFamily: 'Antd');
  static const IconData message = IconData(0xe79d, fontFamily: 'Antd');
  static const IconData closecirclefill = IconData(0xe89d, fontFamily: 'Antd');
  static const IconData fastbackward = IconData(0xe99d, fontFamily: 'Antd');
  static const IconData dashboard = IconData(0xe79e, fontFamily: 'Antd');
  static const IconData infocirclefill = IconData(0xe89e, fontFamily: 'Antd');
  static const IconData forward = IconData(0xe99e, fontFamily: 'Antd');
  static const IconData issuesclose = IconData(0xe79f, fontFamily: 'Antd');
  static const IconData upcirclefill = IconData(0xe89f, fontFamily: 'Antd');
  static const IconData fastforward = IconData(0xe99f, fontFamily: 'Antd');
  static const IconData poweroff = IconData(0xe7a0, fontFamily: 'Antd');
  static const IconData rightcirclefill = IconData(0xe8a0, fontFamily: 'Antd');
  static const IconData search = IconData(0xe9a0, fontFamily: 'Antd');
  static const IconData logout = IconData(0xe7a1, fontFamily: 'Antd');
  static const IconData pluscirclefill = IconData(0xe8a1, fontFamily: 'Antd');
  static const IconData retweet = IconData(0xe9a1, fontFamily: 'Antd');
  static const IconData piechart = IconData(0xe7a2, fontFamily: 'Antd');
  static const IconData questioncirclefill = IconData(0xe8a2, fontFamily: 'Antd');
  static const IconData login = IconData(0xe9a2, fontFamily: 'Antd');
  static const IconData setting = IconData(0xe7a3, fontFamily: 'Antd');
  static const IconData eurocirclefill = IconData(0xe8a3, fontFamily: 'Antd');
  static const IconData stepbackward = IconData(0xe9a3, fontFamily: 'Antd');
  static const IconData eye = IconData(0xe7a4, fontFamily: 'Antd');
  static const IconData frownfill = IconData(0xe8a4, fontFamily: 'Antd');
  static const IconData stepforward = IconData(0xe9a4, fontFamily: 'Antd');
  static const IconData location = IconData(0xe7a5, fontFamily: 'Antd');
  static const IconData copyrightcirclefil = IconData(0xe8a5, fontFamily: 'Antd');
  static const IconData swapright = IconData(0xe9a5, fontFamily: 'Antd');
  static const IconData editsquare = IconData(0xe7a6, fontFamily: 'Antd');
  static const IconData cicirclefill = IconData(0xe8a6, fontFamily: 'Antd');
  static const IconData swapleft = IconData(0xe9a6, fontFamily: 'Antd');
  static const IconData export = IconData(0xe7a7, fontFamily: 'Antd');
  static const IconData compassfill = IconData(0xe8a7, fontFamily: 'Antd');
  static const IconData woman = IconData(0xe9a7, fontFamily: 'Antd');
  static const IconData save = IconData(0xe7a8, fontFamily: 'Antd');
  static const IconData dollarcirclefill = IconData(0xe8a8, fontFamily: 'Antd');
  static const IconData plus = IconData(0xe9a8, fontFamily: 'Antd');
  static const IconData import = IconData(0xe7a9, fontFamily: 'Antd');
  static const IconData poweroffcirclefill = IconData(0xe8a9, fontFamily: 'Antd');
  static const IconData eyeclosefill = IconData(0xe9a9, fontFamily: 'Antd');
  static const IconData appstore = IconData(0xe7aa, fontFamily: 'Antd');
  static const IconData mehfill = IconData(0xe8aa, fontFamily: 'Antd');
  static const IconData eyeclose = IconData(0xe9aa, fontFamily: 'Antd');
  static const IconData closesquare = IconData(0xe7ab, fontFamily: 'Antd');
  static const IconData playcirclefill = IconData(0xe8ab, fontFamily: 'Antd');
  static const IconData clear = IconData(0xe9ab, fontFamily: 'Antd');
  static const IconData downsquare = IconData(0xe7ac, fontFamily: 'Antd');
  static const IconData poundcirclefill = IconData(0xe8ac, fontFamily: 'Antd');
  static const IconData collapse = IconData(0xe9ac, fontFamily: 'Antd');
  static const IconData layout = IconData(0xe7ad, fontFamily: 'Antd');
  static const IconData smilefill = IconData(0xe8ad, fontFamily: 'Antd');
  static const IconData expand = IconData(0xe9ad, fontFamily: 'Antd');
  static const IconData leftsquare = IconData(0xe7ae, fontFamily: 'Antd');
  static const IconData stopfill = IconData(0xe8ae, fontFamily: 'Antd');
  static const IconData deletecolumn = IconData(0xe9ae, fontFamily: 'Antd');
  static const IconData playsquare = IconData(0xe7af, fontFamily: 'Antd');
  static const IconData warningcirclefill = IconData(0xe8af, fontFamily: 'Antd');
  static const IconData mergecells = IconData(0xe9af, fontFamily: 'Antd');
  static const IconData control = IconData(0xe7b0, fontFamily: 'Antd');
  static const IconData timecirclefill = IconData(0xe8b0, fontFamily: 'Antd');
  static const IconData subnode = IconData(0xe9b0, fontFamily: 'Antd');
  static const IconData codelibrary = IconData(0xe7b1, fontFamily: 'Antd');
  static const IconData trademarkcirclefil = IconData(0xe8b1, fontFamily: 'Antd');
  static const IconData rotateleft = IconData(0xe9b1, fontFamily: 'Antd');
  static const IconData detail = IconData(0xe7b2, fontFamily: 'Antd');
  static const IconData yuancirclefill = IconData(0xe8b2, fontFamily: 'Antd');
  static const IconData rotateright = IconData(0xe9b2, fontFamily: 'Antd');
  static const IconData minussquare = IconData(0xe7b3, fontFamily: 'Antd');
  static const IconData heartfill = IconData(0xe8b3, fontFamily: 'Antd');
  static const IconData insertrowbelow = IconData(0xe9b3, fontFamily: 'Antd');
  static const IconData plussquare = IconData(0xe7b4, fontFamily: 'Antd');
  static const IconData piechartcirclefil = IconData(0xe8b4, fontFamily: 'Antd');
  static const IconData insertrowabove = IconData(0xe9b4, fontFamily: 'Antd');
  static const IconData rightsquare = IconData(0xe7b5, fontFamily: 'Antd');
  static const IconData dashboardfill = IconData(0xe8b5, fontFamily: 'Antd');
  static const IconData tableOut = IconData(0xe9b5, fontFamily: 'Antd');
  static const IconData project = IconData(0xe7b6, fontFamily: 'Antd');
  static const IconData messagefill = IconData(0xe8b6, fontFamily: 'Antd');
  static const IconData solitcells = IconData(0xe9b6, fontFamily: 'Antd');
  static const IconData wallet = IconData(0xe7b7, fontFamily: 'Antd');
  static const IconData checksquarefill = IconData(0xe8b7, fontFamily: 'Antd');
  static const IconData formatpainter = IconData(0xe9b7, fontFamily: 'Antd');
  static const IconData upsquare = IconData(0xe7b8, fontFamily: 'Antd');
  static const IconData downsquarefill = IconData(0xe8b8, fontFamily: 'Antd');
  static const IconData insertrowright = IconData(0xe9b8, fontFamily: 'Antd');
  static const IconData calculator = IconData(0xe7b9, fontFamily: 'Antd');
  static const IconData minussquarefill = IconData(0xe8b9, fontFamily: 'Antd');
  static const IconData formatpainterfill = IconData(0xe9b9, fontFamily: 'Antd');
  static const IconData interation = IconData(0xe7ba, fontFamily: 'Antd');
  static const IconData closesquarefill = IconData(0xe8ba, fontFamily: 'Antd');
  static const IconData insertrowleft = IconData(0xe9ba, fontFamily: 'Antd');
  static const IconData checksquare = IconData(0xe7bb, fontFamily: 'Antd');
  static const IconData codelibraryfill = IconData(0xe8bb, fontFamily: 'Antd');
  static const IconData translate = IconData(0xe9bb, fontFamily: 'Antd');
  static const IconData border = IconData(0xe7bc, fontFamily: 'Antd');
  static const IconData leftsquarefill = IconData(0xe8bc, fontFamily: 'Antd');
  static const IconData deleterow = IconData(0xe9bc, fontFamily: 'Antd');
  static const IconData borderouter = IconData(0xe7bd, fontFamily: 'Antd');
  static const IconData playsquarefill = IconData(0xe8bd, fontFamily: 'Antd');
  static const IconData sisternode = IconData(0xe9bd, fontFamily: 'Antd');
  static const IconData bordertop = IconData(0xe7be, fontFamily: 'Antd');
  static const IconData upsquarefill = IconData(0xe8be, fontFamily: 'Antd');
  static const IconData fieldnumber = IconData(0xe9be, fontFamily: 'Antd');
  static const IconData borderbottom = IconData(0xe7bf, fontFamily: 'Antd');
  static const IconData rightsquarefill = IconData(0xe8bf, fontFamily: 'Antd');
  static const IconData fieldstring = IconData(0xe9bf, fontFamily: 'Antd');
  static const IconData borderleft = IconData(0xe7c0, fontFamily: 'Antd');
  static const IconData plussquarefill = IconData(0xe8c0, fontFamily: 'Antd');
  static const IconData function = IconData(0xe9c0, fontFamily: 'Antd');
  static const IconData borderright = IconData(0xe7c1, fontFamily: 'Antd');
  static const IconData accountbookfill = IconData(0xe8c1, fontFamily: 'Antd');
  static const IconData fieldtime = IconData(0xe9c1, fontFamily: 'Antd');
  static const IconData borderinner = IconData(0xe7c2, fontFamily: 'Antd');
  static const IconData carryoutfill = IconData(0xe8c2, fontFamily: 'Antd');
  static const IconData gif = IconData(0xe9c2, fontFamily: 'Antd');
  static const IconData borderverticle = IconData(0xe7c3, fontFamily: 'Antd');
  static const IconData calendarfill = IconData(0xe8c3, fontFamily: 'Antd');
  static const IconData partition = IconData(0xe9c3, fontFamily: 'Antd');
  static const IconData borderhorizontal = IconData(0xe7c4, fontFamily: 'Antd');
  static const IconData calculatorfill = IconData(0xe8c4, fontFamily: 'Antd');
  static const IconData index = IconData(0xe9c4, fontFamily: 'Antd');
  static const IconData radiusbottomleft = IconData(0xe7c5, fontFamily: 'Antd');
  static const IconData interationfill = IconData(0xe8c5, fontFamily: 'Antd');
  static const IconData storedprocedure = IconData(0xe9c5, fontFamily: 'Antd');
  static const IconData radiusbottomright = IconData(0xe7c6, fontFamily: 'Antd');
  static const IconData projectfill = IconData(0xe8c6, fontFamily: 'Antd');
  static const IconData fieldbinary = IconData(0xe9c6, fontFamily: 'Antd');
  static const IconData radiusupleft = IconData(0xe7c7, fontFamily: 'Antd');
  static const IconData detailfill = IconData(0xe8c7, fontFamily: 'Antd');
  static const IconData consolesql = IconData(0xe9c7, fontFamily: 'Antd');
  static const IconData radiusupright = IconData(0xe7c8, fontFamily: 'Antd');
  static const IconData savefill = IconData(0xe8c8, fontFamily: 'Antd');
  static const IconData oneColonOne = IconData(0xe9c8, fontFamily: 'Antd');
  static const IconData radiussetting = IconData(0xe7c9, fontFamily: 'Antd');
  static const IconData walletfill = IconData(0xe8c9, fontFamily: 'Antd');
  static const IconData aim = IconData(0xe9c9, fontFamily: 'Antd');
  static const IconData adduser = IconData(0xe7ca, fontFamily: 'Antd');
  static const IconData controlfill = IconData(0xe8ca, fontFamily: 'Antd');
  static const IconData compress = IconData(0xe9ca, fontFamily: 'Antd');
  static const IconData deleteteam = IconData(0xe7cb, fontFamily: 'Antd');
  static const IconData layoutfill = IconData(0xe8cb, fontFamily: 'Antd');
  static const IconData expend = IconData(0xe9cb, fontFamily: 'Antd');
  static const IconData deleteuser = IconData(0xe7cc, fontFamily: 'Antd');
  static const IconData appstorefill = IconData(0xe8cc, fontFamily: 'Antd');
  static const IconData folderview = IconData(0xe9cc, fontFamily: 'Antd');
  static const IconData addteam = IconData(0xe7cd, fontFamily: 'Antd');
  static const IconData mobilefill = IconData(0xe8cd, fontFamily: 'Antd');
  static const IconData filegif = IconData(0xe9cd, fontFamily: 'Antd');
  static const IconData user = IconData(0xe7ce, fontFamily: 'Antd');
  static const IconData tabletfill = IconData(0xe8ce, fontFamily: 'Antd');
  static const IconData group = IconData(0xe9ce, fontFamily: 'Antd');
  static const IconData team = IconData(0xe7cf, fontFamily: 'Antd');
  static const IconData bookfill = IconData(0xe8cf, fontFamily: 'Antd');
  static const IconData send = IconData(0xe9cf, fontFamily: 'Antd');
  static const IconData areachart = IconData(0xe7d0, fontFamily: 'Antd');
  static const IconData redenvelopefill = IconData(0xe8d0, fontFamily: 'Antd');
  static const IconData report = IconData(0xe9d0, fontFamily: 'Antd');
  static const IconData linechart = IconData(0xe7d1, fontFamily: 'Antd');
  static const IconData safetycertificatef = IconData(0xe8d1, fontFamily: 'Antd');
  static const IconData view = IconData(0xe9d1, fontFamily: 'Antd');
  static const IconData barchart = IconData(0xe7d2, fontFamily: 'Antd');
  static const IconData propertysafetyfill = IconData(0xe8d2, fontFamily: 'Antd');
  static const IconData shortcut = IconData(0xe9d2, fontFamily: 'Antd');
  static const IconData pointmap = IconData(0xe7d3, fontFamily: 'Antd');
  static const IconData insurancefill = IconData(0xe8d3, fontFamily: 'Antd');
  static const IconData ungroup = IconData(0xe9d3, fontFamily: 'Antd');
  static const IconData container = IconData(0xe7d4, fontFamily: 'Antd');
  static const IconData securityscanfill = IconData(0xe8d4, fontFamily: 'Antd');
  static const IconData database = IconData(0xe7d5, fontFamily: 'Antd');
  static const IconData fileexclamationfil = IconData(0xe8d5, fontFamily: 'Antd');
  static const IconData sever = IconData(0xe7d6, fontFamily: 'Antd');
  static const IconData fileaddfill = IconData(0xe8d6, fontFamily: 'Antd');
  static const IconData mobile = IconData(0xe7d7, fontFamily: 'Antd');
  static const IconData filefill = IconData(0xe8d7, fontFamily: 'Antd');
  static const IconData tablet = IconData(0xe7d8, fontFamily: 'Antd');
  static const IconData fileexcelfill = IconData(0xe8d8, fontFamily: 'Antd');
  static const IconData redenvelope = IconData(0xe7d9, fontFamily: 'Antd');
  static const IconData filemarkdownfill = IconData(0xe8d9, fontFamily: 'Antd');
  static const IconData book = IconData(0xe7da, fontFamily: 'Antd');
  static const IconData filetextfill = IconData(0xe8da, fontFamily: 'Antd');
  static const IconData filedone = IconData(0xe7db, fontFamily: 'Antd');
  static const IconData filepptfill = IconData(0xe8db, fontFamily: 'Antd');
  static const IconData reconciliation = IconData(0xe7dc, fontFamily: 'Antd');
  static const IconData fileunknownfill = IconData(0xe8dc, fontFamily: 'Antd');
  static const IconData fileexception = IconData(0xe7dd, fontFamily: 'Antd');
  static const IconData filewordfill = IconData(0xe8dd, fontFamily: 'Antd');
  static const IconData filesync = IconData(0xe7de, fontFamily: 'Antd');
  static const IconData filezipfill = IconData(0xe8de, fontFamily: 'Antd');
  static const IconData filesearch = IconData(0xe7df, fontFamily: 'Antd');
  static const IconData filepdffill = IconData(0xe8df, fontFamily: 'Antd');
  static const IconData solution = IconData(0xe7e0, fontFamily: 'Antd');
  static const IconData fileimagefill = IconData(0xe8e0, fontFamily: 'Antd');
  static const IconData fileprotect = IconData(0xe7e1, fontFamily: 'Antd');
  static const IconData difffill = IconData(0xe8e1, fontFamily: 'Antd');
  static const IconData fileadd = IconData(0xe7e2, fontFamily: 'Antd');
  static const IconData filecopyfill = IconData(0xe8e2, fontFamily: 'Antd');
  static const IconData fileexcel = IconData(0xe7e3, fontFamily: 'Antd');
  static const IconData snippetsfill = IconData(0xe8e3, fontFamily: 'Antd');
  static const IconData fileexclamation = IconData(0xe7e4, fontFamily: 'Antd');
  static const IconData batchfoldingfill = IconData(0xe8e4, fontFamily: 'Antd');
  static const IconData filepdf = IconData(0xe7e5, fontFamily: 'Antd');
  static const IconData reconciliationfill = IconData(0xe8e5, fontFamily: 'Antd');
  static const IconData fileimage = IconData(0xe7e6, fontFamily: 'Antd');
  static const IconData folderaddfill = IconData(0xe8e6, fontFamily: 'Antd');
  static const IconData filemarkdown = IconData(0xe7e7, fontFamily: 'Antd');
  static const IconData folderfill = IconData(0xe8e7, fontFamily: 'Antd');
  static const IconData fileunknown = IconData(0xe7e8, fontFamily: 'Antd');
  static const IconData folderopenfill = IconData(0xe8e8, fontFamily: 'Antd');
  static const IconData fileppt = IconData(0xe7e9, fontFamily: 'Antd');
  static const IconData databasefill = IconData(0xe8e9, fontFamily: 'Antd');
  static const IconData fileword = IconData(0xe7ea, fontFamily: 'Antd');
  static const IconData containerfill = IconData(0xe8ea, fontFamily: 'Antd');
  static const IconData file = IconData(0xe7eb, fontFamily: 'Antd');
  static const IconData severfill = IconData(0xe8eb, fontFamily: 'Antd');
  static const IconData filezip = IconData(0xe7ec, fontFamily: 'Antd');
  static const IconData calendarcheckfill = IconData(0xe8ec, fontFamily: 'Antd');
  static const IconData filetext = IconData(0xe7ed, fontFamily: 'Antd');
  static const IconData imagefill = IconData(0xe8ed, fontFamily: 'Antd');
  static const IconData filecopy = IconData(0xe7ee, fontFamily: 'Antd');
  static const IconData idcardfill = IconData(0xe8ee, fontFamily: 'Antd');
  static const IconData snippets = IconData(0xe7ef, fontFamily: 'Antd');
  static const IconData creditcardfill = IconData(0xe8ef, fontFamily: 'Antd');
  static const IconData audit = IconData(0xe7f0, fontFamily: 'Antd');
  static const IconData fundfill = IconData(0xe8f0, fontFamily: 'Antd');
  static const IconData diff = IconData(0xe7f1, fontFamily: 'Antd');
  static const IconData readfill = IconData(0xe8f1, fontFamily: 'Antd');
  static const IconData batchfolding = IconData(0xe7f2, fontFamily: 'Antd');
  static const IconData contactsfill = IconData(0xe8f2, fontFamily: 'Antd');
  static const IconData securityscan = IconData(0xe7f3, fontFamily: 'Antd');
  static const IconData deletefill = IconData(0xe8f3, fontFamily: 'Antd');
  static const IconData propertysafety = IconData(0xe7f4, fontFamily: 'Antd');
  static const IconData notificationfill = IconData(0xe8f4, fontFamily: 'Antd');
  static const IconData safetycertificate = IconData(0xe7f5, fontFamily: 'Antd');
  static const IconData flagfill = IconData(0xe8f5, fontFamily: 'Antd');
  static const IconData insurance = IconData(0xe7f6, fontFamily: 'Antd');
  static const IconData moneycollectfill = IconData(0xe8f6, fontFamily: 'Antd');
  static const IconData alert = IconData(0xe7f7, fontFamily: 'Antd');
  static const IconData medicineboxfill = IconData(0xe8f7, fontFamily: 'Antd');
  static const IconData delete = IconData(0xe7f8, fontFamily: 'Antd');
  static const IconData restfill = IconData(0xe8f8, fontFamily: 'Antd');
  static const IconData hourglass = IconData(0xe7f9, fontFamily: 'Antd');
  static const IconData shoppingfill = IconData(0xe8f9, fontFamily: 'Antd');
  static const IconData bulb = IconData(0xe7fa, fontFamily: 'Antd');
  static const IconData skinfill = IconData(0xe8fa, fontFamily: 'Antd');
  static const IconData experiment = IconData(0xe7fb, fontFamily: 'Antd');
  static const IconData videofill = IconData(0xe8fb, fontFamily: 'Antd');
  static const IconData bell = IconData(0xe7fc, fontFamily: 'Antd');
  static const IconData soundfill = IconData(0xe8fc, fontFamily: 'Antd');
  static const IconData trophy = IconData(0xe7fd, fontFamily: 'Antd');
  static const IconData bulbfill = IconData(0xe8fd, fontFamily: 'Antd');
  static const IconData rest = IconData(0xe7fe, fontFamily: 'Antd');
  static const IconData bellfill = IconData(0xe8fe, fontFamily: 'Antd');
  static const IconData usb = IconData(0xe7ff, fontFamily: 'Antd');
  static const IconData filterfill = IconData(0xe8ff, fontFamily: 'Antd');
  static const IconData skin = IconData(0xe800, fontFamily: 'Antd');
  static const IconData firefill = IconData(0xe900, fontFamily: 'Antd');
  static const IconData home = IconData(0xe801, fontFamily: 'Antd');
  static const IconData funnelplotfill = IconData(0xe901, fontFamily: 'Antd');
  static const IconData bank = IconData(0xe802, fontFamily: 'Antd');
  static const IconData giftfill = IconData(0xe902, fontFamily: 'Antd');
  static const IconData filter = IconData(0xe803, fontFamily: 'Antd');
  static const IconData hourglassfill = IconData(0xe903, fontFamily: 'Antd');
  static const IconData funnelplot = IconData(0xe804, fontFamily: 'Antd');
  static const IconData homefill = IconData(0xe904, fontFamily: 'Antd');
  static const IconData like = IconData(0xe805, fontFamily: 'Antd');
  static const IconData trophyfill = IconData(0xe905, fontFamily: 'Antd');
  static const IconData unlike = IconData(0xe806, fontFamily: 'Antd');
  static const IconData locationfill = IconData(0xe906, fontFamily: 'Antd');
  static const IconData unlock = IconData(0xe807, fontFamily: 'Antd');
  static const IconData cloudfill = IconData(0xe907, fontFamily: 'Antd');
  static const IconData lock = IconData(0xe808, fontFamily: 'Antd');
  static const IconData customerservicefill = IconData(0xe908, fontFamily: 'Antd');
  static const IconData customerservice = IconData(0xe809, fontFamily: 'Antd');
  static const IconData experimentfill = IconData(0xe909, fontFamily: 'Antd');
  static const IconData flag = IconData(0xe80a, fontFamily: 'Antd');
  static const IconData eyefill = IconData(0xe90a, fontFamily: 'Antd');
  static const IconData moneycollect = IconData(0xe80b, fontFamily: 'Antd');
  static const IconData likefill = IconData(0xe90b, fontFamily: 'Antd');
  static const IconData medicinebox = IconData(0xe80c, fontFamily: 'Antd');
  static const IconData lockfill = IconData(0xe90c, fontFamily: 'Antd');
  static const IconData shop = IconData(0xe80d, fontFamily: 'Antd');
  static const IconData unlikefill = IconData(0xe90d, fontFamily: 'Antd');
  static const IconData rocket = IconData(0xe80e, fontFamily: 'Antd');
  static const IconData starfill = IconData(0xe90e, fontFamily: 'Antd');
  static const IconData shopping = IconData(0xe80f, fontFamily: 'Antd');
  static const IconData unlockfill = IconData(0xe90f, fontFamily: 'Antd');
  static const IconData folder = IconData(0xe810, fontFamily: 'Antd');
  static const IconData alertfill = IconData(0xe910, fontFamily: 'Antd');
  static const IconData folderopen = IconData(0xe811, fontFamily: 'Antd');
  static const IconData apifill = IconData(0xe911, fontFamily: 'Antd');
  static const IconData folderadd = IconData(0xe812, fontFamily: 'Antd');
  static const IconData highlightfill = IconData(0xe912, fontFamily: 'Antd');
  static const IconData deploymentunit = IconData(0xe813, fontFamily: 'Antd');
  static const IconData phonefill = IconData(0xe913, fontFamily: 'Antd');
  static const IconData accountbook = IconData(0xe814, fontFamily: 'Antd');
  static const IconData editfill = IconData(0xe914, fontFamily: 'Antd');
  static const IconData contacts = IconData(0xe815, fontFamily: 'Antd');
  static const IconData pushpinfill = IconData(0xe915, fontFamily: 'Antd');
  static const IconData carryout = IconData(0xe816, fontFamily: 'Antd');
  static const IconData rocketfill = IconData(0xe916, fontFamily: 'Antd');
  static const IconData calendarcheck = IconData(0xe817, fontFamily: 'Antd');
  static const IconData thunderboltfill = IconData(0xe917, fontFamily: 'Antd');
  static const IconData calendar = IconData(0xe818, fontFamily: 'Antd');
  static const IconData tagfill = IconData(0xe918, fontFamily: 'Antd');
  static const IconData scan = IconData(0xe819, fontFamily: 'Antd');
  static const IconData wrenchfill = IconData(0xe919, fontFamily: 'Antd');
  static const IconData select = IconData(0xe81a, fontFamily: 'Antd');
  static const IconData tagsfill = IconData(0xe91a, fontFamily: 'Antd');
  static const IconData boxplot = IconData(0xe81b, fontFamily: 'Antd');
  static const IconData bankfill = IconData(0xe91b, fontFamily: 'Antd');
  static const IconData build = IconData(0xe81c, fontFamily: 'Antd');
  static const IconData camerafill = IconData(0xe91c, fontFamily: 'Antd');
  static const IconData sliders = IconData(0xe81d, fontFamily: 'Antd');
  static const IconData errorfill = IconData(0xe91d, fontFamily: 'Antd');
  static const IconData laptop = IconData(0xe81e, fontFamily: 'Antd');
  static const IconData crownfill = IconData(0xe91e, fontFamily: 'Antd');
  static const IconData barcode = IconData(0xe81f, fontFamily: 'Antd');
  static const IconData mailfill = IconData(0xe91f, fontFamily: 'Antd');
  static const IconData camera = IconData(0xe820, fontFamily: 'Antd');
  static const IconData carfill = IconData(0xe920, fontFamily: 'Antd');
  static const IconData cluster = IconData(0xe821, fontFamily: 'Antd');
  static const IconData printerfill = IconData(0xe921, fontFamily: 'Antd');
  static const IconData gateway = IconData(0xe822, fontFamily: 'Antd');
  static const IconData shopfill = IconData(0xe922, fontFamily: 'Antd');
  static const IconData car = IconData(0xe823, fontFamily: 'Antd');
  static const IconData settingfill = IconData(0xe923, fontFamily: 'Antd');
  static const IconData printer = IconData(0xe824, fontFamily: 'Antd');
  static const IconData usbfill = IconData(0xe924, fontFamily: 'Antd');
  static const IconData read = IconData(0xe825, fontFamily: 'Antd');
  static const IconData goldenfill = IconData(0xe925, fontFamily: 'Antd');
  static const IconData cloudserver = IconData(0xe826, fontFamily: 'Antd');
  static const IconData buildfill = IconData(0xe926, fontFamily: 'Antd');
  static const IconData cloudupload = IconData(0xe827, fontFamily: 'Antd');
  static const IconData boxplotfill = IconData(0xe927, fontFamily: 'Antd');
  static const IconData cloud = IconData(0xe828, fontFamily: 'Antd');
  static const IconData slidersfill = IconData(0xe928, fontFamily: 'Antd');
  static const IconData clouddownload = IconData(0xe829, fontFamily: 'Antd');
  static const IconData alibaba = IconData(0xe929, fontFamily: 'Antd');
  static const IconData cloudsync = IconData(0xe82a, fontFamily: 'Antd');
  static const IconData antdesign = IconData(0xe92a, fontFamily: 'Antd');
  static const IconData video = IconData(0xe82b, fontFamily: 'Antd');
  static const IconData antcloud = IconData(0xe92b, fontFamily: 'Antd');
  static const IconData notification = IconData(0xe82c, fontFamily: 'Antd');
  static const IconData behance = IconData(0xe92c, fontFamily: 'Antd');
  static const IconData sound = IconData(0xe82d, fontFamily: 'Antd');
  static const IconData googleplus = IconData(0xe92d, fontFamily: 'Antd');
  static const IconData radarchart = IconData(0xe82e, fontFamily: 'Antd');
  static const IconData medium = IconData(0xe92e, fontFamily: 'Antd');
  static const IconData qrcode = IconData(0xe82f, fontFamily: 'Antd');
  static const IconData google = IconData(0xe92f, fontFamily: 'Antd');
  static const IconData fund = IconData(0xe830, fontFamily: 'Antd');
  static const IconData ie = IconData(0xe930, fontFamily: 'Antd');
  static const IconData image = IconData(0xe831, fontFamily: 'Antd');
  static const IconData amazon = IconData(0xe931, fontFamily: 'Antd');
  static const IconData mail = IconData(0xe832, fontFamily: 'Antd');
  static const IconData slack = IconData(0xe932, fontFamily: 'Antd');
  static const IconData table = IconData(0xe833, fontFamily: 'Antd');
  static const IconData alipay = IconData(0xe933, fontFamily: 'Antd');
  static const IconData idcard = IconData(0xe834, fontFamily: 'Antd');
  static const IconData taobao = IconData(0xe934, fontFamily: 'Antd');
  static const IconData creditcard = IconData(0xe835, fontFamily: 'Antd');
  static const IconData zhihu = IconData(0xe935, fontFamily: 'Antd');
  static const IconData heart = IconData(0xe836, fontFamily: 'Antd');
  static const IconData html5 = IconData(0xe936, fontFamily: 'Antd');
  static const IconData block = IconData(0xe837, fontFamily: 'Antd');
  static const IconData linkedin = IconData(0xe937, fontFamily: 'Antd');
  static const IconData error = IconData(0xe838, fontFamily: 'Antd');
  static const IconData yahoo = IconData(0xe938, fontFamily: 'Antd');
  static const IconData star = IconData(0xe839, fontFamily: 'Antd');
  static const IconData facebook = IconData(0xe939, fontFamily: 'Antd');
  static const IconData gold = IconData(0xe83a, fontFamily: 'Antd');
  static const IconData skype = IconData(0xe93a, fontFamily: 'Antd');
  static const IconData heatmap = IconData(0xe83b, fontFamily: 'Antd');
  static const IconData codesandbox = IconData(0xe93b, fontFamily: 'Antd');
  static const IconData wifi = IconData(0xe83c, fontFamily: 'Antd');
  static const IconData chrome = IconData(0xe93c, fontFamily: 'Antd');
  static const IconData attachment = IconData(0xe83d, fontFamily: 'Antd');
  static const IconData codepen = IconData(0xe93d, fontFamily: 'Antd');
  static const IconData edit = IconData(0xe83e, fontFamily: 'Antd');
  static const IconData aliwangwang = IconData(0xe93e, fontFamily: 'Antd');
  static const IconData key = IconData(0xe83f, fontFamily: 'Antd');
  static const IconData apple = IconData(0xe93f, fontFamily: 'Antd');
  static const IconData api = IconData(0xe840, fontFamily: 'Antd');
  static const IconData android = IconData(0xe940, fontFamily: 'Antd');
  static const IconData disconnect = IconData(0xe841, fontFamily: 'Antd');
  static const IconData sketch = IconData(0xe941, fontFamily: 'Antd');
  static const IconData highlight = IconData(0xe842, fontFamily: 'Antd');
  static const IconData gitlab = IconData(0xe942, fontFamily: 'Antd');
  static const IconData monitor = IconData(0xe843, fontFamily: 'Antd');
  static const IconData dribbble = IconData(0xe943, fontFamily: 'Antd');
  static const IconData link = IconData(0xe844, fontFamily: 'Antd');
  static const IconData instagram = IconData(0xe944, fontFamily: 'Antd');
  static const IconData man = IconData(0xe845, fontFamily: 'Antd');
  static const IconData reddit = IconData(0xe945, fontFamily: 'Antd');
  static const IconData percentage = IconData(0xe846, fontFamily: 'Antd');
  static const IconData windows = IconData(0xe946, fontFamily: 'Antd');
  static const IconData pushpin = IconData(0xe847, fontFamily: 'Antd');
  static const IconData yuque = IconData(0xe947, fontFamily: 'Antd');
  static const IconData phone = IconData(0xe848, fontFamily: 'Antd');
  static const IconData youtube = IconData(0xe948, fontFamily: 'Antd');
  static const IconData shake = IconData(0xe849, fontFamily: 'Antd');
  static const IconData gitlabfill = IconData(0xe949, fontFamily: 'Antd');
  static const IconData tag = IconData(0xe84a, fontFamily: 'Antd');
  static const IconData dropbox = IconData(0xe94a, fontFamily: 'Antd');
}
